// lib/services/language_service.dart
import 'package:flutter/material.dart';

class LanguageService {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  // 監聽目前語系（預設繁體中文 zh_TW）
  final ValueNotifier<Locale> currentLocale = ValueNotifier(const Locale('zh', 'TW'));

  // 取得當前語言名稱
  String get currentLanguageName {
    return currentLocale.value.languageCode == 'en' ? 'English' : '繁體中文';
  }

  // 切換語言
  void changeLanguage(String langName) {
    if (langName == 'English') {
      currentLocale.value = const Locale('en', 'US');
    } else {
      currentLocale.value = const Locale('zh', 'TW');
    }
  }

  // 查表翻譯輔助函式
  static String tr(BuildContext context, String key) {
    final langCode = Localizations.localeOf(context).languageCode;
    return _localizedStrings[langCode]?[key] ??
        _localizedStrings['zh']?[key] ??
        key;
  }

  static String trCurrent(String key) {
    final langCode = LanguageService().currentLocale.value.languageCode;
    return _localizedStrings[langCode]?[key] ??
        _localizedStrings['zh']?[key] ??
        key;
  }

  // 行程外主要頁面之多語系對照字典
  static const Map<String, Map<String, String>> _localizedStrings = {
    'zh': {
      // 全域與頂部導航
      'guide': '使用指南',
      'login': '登入',
      'account_center': '帳號中心',
      'logout': '登出帳號',
      'logout_success': '已安全登出 🌿',
      'guest_traveler': '訪客旅人',
      'login_prompt': '登入以同步自訂行程與收藏',

      // 底部導航
      'nav_home': '首頁',
      'nav_trip': '行程安排',
      'nav_profile': '個人',
      'nav_settings': '設定',

      // 首頁 (HomePage)
      'popular_trips': '可以參考的行程',
      'view_trip': '查看行程',
      'spot_recommendations': '景點推薦',
      'view_detail': '詳細資訊',
      'distance_sort': '依距離排序',
      'load_places_failed': '讀取景點失敗',
      'no_places_available': '目前尚無景點資料',
      'manual_schedule': '手動排程',
      'min': '分鐘',

      // 行程安排頁 (TripPage)
      'create_trip': '建立新行程',
      'trip_basic_info': '旅遊基本資訊',
      'trip_name': '行程名稱',
      'trip_date': '旅遊日期',
      'select_trip_date': '請選擇旅遊日期',
      'trip_location': '旅遊地點',
      'trip_people': '旅遊人數',
      'budget_level': '預算等級',
      'travel_pref_trip': '旅遊偏好',
      'other_requirements': '其他需求',

      // 個人收藏頁 (ProfilePage)
      'my_favorites': '我的收藏',
      'spots': '景點',
      'itinerary': '行程',
      'my_folders': '我的資料夾',
      'create_folder': '建立資料夾',
      'add_to_folder': '加入資料夾',
      'add_to_trip': '加入行程',
      'cancel_fav': '取消收藏',
      'personal_space': '個人空間',
      'my_trips': '我的行程',
      'my_trips_desc': '你親自規劃並儲存的旅程',
      'empty_trips': '尚未有儲存的行程，完成規劃後點擊「匯出」即可存入 🌿',
      'saved_spots': '收藏景點',
      'empty_spots': '尚未收藏任何景點',
      'saved_trips': '收藏行程',
      'saved_folders': '收藏資料夾',
      'empty_folders': '尚未建立任何資料夾',
      'please_login_first': '請先登入帳號',
      'load_trips_failed': '讀取行程失敗',
      'delete_trip': '刪除行程',
      'delete_folder': '刪除資料夾',
      'delete_item_confirm': '確定要刪除「{name}」嗎？此操作無法復原。',
      'delete_action': '刪除',
      'delete_success': '已刪除',
      'delete_failed': '刪除失敗，請稍後再試',

      // 設定頁 (SettingsPage)
      'settings_title': '設定',
      'logged_out_safe': '已安全登出',
      'logged_out_safe_leaf': '已安全登出 🌿',
      'logout_account': '登出帳號',
      'traveler': '旅人',
      'login_sync_hint': '登入以同步自訂行程與收藏',
      'login_action': '登入',
      'account_settings': '個人帳號設置',
      'edit_profile': '編輯個人資料',
      'edit_profile_sub': '修改頭像、暱稱與個人簡介',
      'travel_pref': '旅遊偏好設定',
      'travel_pref_sub': '海島放鬆、戶外探險、人文美食',
      'notifications': '行程與推播通知',
      'notifications_sub': '接收景點時間提醒與優惠資訊',
      'system_settings': '頁面與系統設定',
      'dark_mode': '深色模式',
      'dark_mode_sub': '降低低光源環境下的視覺刺眼感',
      'language_setting': '語言設定',
      'clear_cache': '清除暫存資料',
      'clear_cache_sub': '已使用 48.5 MB 空間',
      'clear_cache_title': '清除暫存資料',
      'clear_cache_content': '將清除暫存的景點圖片與離線資料，這不會影響你的收藏或自訂行程。',
      'clear_cache_confirm': '確認清除',
      'clear_cache_cancel': '取消',
      'clear_cache_success': '已成功清除暫存檔案 🧹',
      'review_guide': '重新檢視使用指南',
      'about_app': '關於陪伴旅伴 App',
      'select_language': '選擇語言',

      //register screen
      'register_title': '註冊帳號',
      'register_email': '電子郵件',
      'register_password': '密碼',
      'confirm_password': '確認密碼',
      'terms_of_service': '服務條款',
      'privacy_policy': '隱私政策',

      // Shared page labels and messages
      'place_category_attraction': '景點',
      'place_category_restaurant': '餐廳',
      'place_category_accommodation': '住宿',
      'place_detail_intro': '介紹',
      'place_detail_address': '地址',
      'place_detail_navigation': '導航',
      'place_detail_empty_description': '暫無詳細介紹',
      'place_detail_stay': '建議停留',
      'place_detail_minutes': '分鐘',
      'place_favorite_added': '已將「{place}」加入收藏 ⭐️',
      'place_favorite_removed': '已將「{place}」移出收藏',
      'place_phone_unavailable': '無法開啟電話功能',
      'place_website_invalid': '網站網址格式不正確',
      'place_website_unavailable': '無法開啟網站',
      'search_trips_hint': '搜尋行程...',
      'search_you_might_like': '你可能會喜歡......',
      'search_sort': '(排序方式)',
      'search_trip_use_count': '(使用次數: {count})',
      'profile_view_info': '查看資訊',
      'profile_folder_empty_detail': '資料夾內尚無景點\n可在景點右下角選單選擇「加入資料夾」',
      'profile_no_folders': '目前尚無任何資料夾',
      'profile_close': '關閉',
      'profile_create_folder': '建立新資料夾',
      'profile_folder_name_hint': '請輸入資料夾名稱',
      'profile_cancel': '取消',
      'profile_create': '建立',
      'profile_folder_failed': '建立資料夾失敗，請確認是否已登入',
      'profile_folder_add_failed': '加入失敗，請稍後再試',
      'profile_unnamed_trip': '未命名行程',
      'profile_image': '圖片',
      'guide_finish': '點擊完成 ❯',
      'guide_next': '點擊下一步 ❯',
      'guide_skip': '略過導引',
      'edit_profile_title': '編輯個人資料',
      'edit_profile_change_avatar': '點擊相機更換頭像',
      'edit_profile_avatar_notice': '更換大頭貼功能（可串接圖片上傳）',
      'edit_profile_default_bio': '熱愛探索世界的旅伴 🌿',
      'edit_profile_nickname': '使用者暱稱',
      'edit_profile_nickname_hint': '請輸入你的暱稱',
      'edit_profile_nickname_required': '暱稱不能為空',
      'edit_profile_email': '綁定信箱 (不可修改)',
      'edit_profile_email_hint': '電子信箱',
      'edit_profile_bio': '個人簡介 / 旅伴名言',
      'edit_profile_bio_hint': '寫下一兩句你的旅遊風格，例如：熱愛戶外探險...',
      'edit_profile_save': '儲存變更',
      'edit_profile_saved': '個人資料已同步更新 ✨',
      'edit_profile_load_failed': '載入資料失敗',
      'edit_profile_save_failed': '儲存失敗',
      'login_success': '登入成功！歡迎回來 🌿',
      'login_invalid': '帳號或密碼錯誤',
      'login_error': '登入過程發生錯誤',
      'login_email_required': '請輸入電子信箱',
      'login_password_required': '請輸入密碼',
      'login_contact_admin': '請聯繫管理員重設密碼',
      'register_action': '註冊帳號',
      'trip_no_spots': '目前沒有可以安排的景點',
      'trip_day_no_spots': '這一天目前沒有安排景點',
      'trip_result_title': '你的行程',
      'guide_settings_title': '使用指南與設定',
      'guide_settings_desc': '點擊這裡可以開啟使用指南，並在設定中切換語言。',
      'guide_nav_title': '快速切換頁面',
      'guide_nav_desc': '使用底部導覽列切換首頁、行程、個人收藏與設定。',
      'home_distance_sort': '依距離排序',
      'home_load_places_failed': '讀取景點失敗',
      'home_no_places': '目前尚無景點資料',
      'trip_select_date_first': '請先選擇旅遊日期',
      'trip_select_budget': '請選擇預算等級',
      'trip_catalog_empty': '目前沒有可讀取的行程資料',
      'trip_preference_parse_failed': 'AI 偏好解析失敗',
      'trip_create_failed': '建立行程失敗',
      'search_hint': '搜尋行程...',
      'search_recommendations': '你可能會喜歡......',
      'search_sort_label': '(排序方式)',
      'search_count_label': '(使用次數: {count})',
      'register_subtitle': '加入我們，開啟你的下一趟探索',
      'register_name_required': '請輸入姓名',
      'register_email_required': '請輸入電子郵件',
      'register_email_invalid': '請輸入有效的電子信箱格式',
      'register_password_short': '密碼至少需 6 碼',
      'register_password_mismatch': '兩次密碼輸入不一致',
      'register_success': '註冊成功！準備開始你的旅程 ✈️',
      'register_failed': '註冊失敗，請稍後再試',
      'register_have_account': '已經有帳號了嗎？',
      'register_login': '立即登入',
      'trip_date_not_selected': '尚未選擇',
      'trip_date_select_prompt': '請選擇旅遊日期',
      'trip_name_example': '例如：台北兩天一夜',
      'trip_people_unit': '人',
      'budget_save': '節省',
      'budget_affordable': '平價',
      'budget_moderate': '適中',
      'budget_upscale': '高級',
      'budget_luxury': '奢華',
      'budget_scale_hint': '1 最省・5 最高',
      'trip_other_requirements_hint': '例如：希望行程悠閒一點，不要安排太多景點',
      'trip_understanding_preferences': '正在理解旅遊需求...',
      'trip_next_step': '下一步',
      'pref_food': '美食',
      'pref_shopping': '購物',
      'pref_culture': '文化',
      'pref_nature': '自然',
      'pref_photography': '攝影',
      'pref_night_view': '夜景',
      'pref_family': '親子',
      'pref_history': '歷史',
      'pref_art': '藝術',
      'route_detail_title': '路線詳細資訊',
      'route_departure': '出發點',
      'route_boarding': '乘車點',
      'route_destination': '目的地',
      'route_walk': '步行',
      'route_minutes': '分鐘',
      'route_under_minute': '1 分鐘內',
      'route_bus': '公車',
      'route_stop_count': '{duration} ({count} 站)',
      'route_wait': '等候 {minutes} 分鐘',
      'recommended_itinerary': '推薦行程',
      'search_places_hint': '搜尋景點、美食、地點...',
      'create_trip_example': '例如：台北一日遊',
      'dialog_cancel': '取消',
      'dialog_create': '建立',
      'add_to_trip_dialog_title': '加入行程',
      'add_to_trip_empty': '目前沒有任何行程',
      'add_to_trip_spot_count': '{count} 個景點',
      'add_to_trip_success': '已將「{place}」加入「{trip}」',
      'planner_title': '安排行程',
      'planner_add_new': '新增{type}',
      'planner_type_schedule': '安排{type}',
      'planner_conflict_title': '旅遊需求有衝突',
      'planner_conflict_message': '部分喜好同時出現在排除條件中，目前會以排除條件為優先：',
      'planner_acknowledge': '我知道了',
      'planner_summary': '景點 {attractions}・餐廳 {restaurants}・住宿 {accommodations}｜固定時間 {fixed}・指定日期 {dated}・自動安排 {automatic}',
      'planner_auto_fill': '智慧補齊景點',
      'planner_generating': '正在安排詳細行程…',
      'planner_finish_generate': '完成安排，產生詳細行程',
      'planner_cancel_wait_estimate': '取消等待，後續改用估算',
      'planner_unscheduled_type': '不限日期／時間的{type}',
      'planner_unscheduled_auto': '這些{type}會由系統自動安排',
      'planner_unscheduled_empty': '目前沒有待安排項目',
      'planner_select_day': '指定日期',
      'planner_adjust_hotel': '調整住宿',
      'planner_remove': '移除',
      'planner_any_day': '不限日期',
      'planner_choose_day_first': '請先指定日期',
      'planner_add_item_first': '請至少加入一個行程項目',
      'planner_generation_failed': '無法產生詳細行程',
      'planner_recommendation_reason': '推薦原因：{reasons}',
      'planner_untimed_title': '待安排時間',
      'planner_timeline_title': '時間軸',
      'planner_no_unscheduled_type': '目前沒有待安排{type}',
      'planner_remove_type': '移除{type}',
      'planner_outside_range': '提醒：此景點並非預設遊玩範圍，但因為是必去景點仍會保留。',
      'planner_recommended_removable': '系統推薦・可自行移除',
      'planner_adjust_accommodation': '調整住宿',
      'planner_select_date': '指定日期',
      'planner_any_date_time': '不限日期／時間',
      'planner_day_time_unlimited': 'Day {day}・時間不限',
      'planner_locked_time': '{time}・已鎖定',
      'planner_preferences_tooltip': '時段、停留與資訊來源',
      'planner_choose_date': '選擇日期',
      'planner_specify_time': '指定時間',
      'planner_date_past': '不能將景點安排在已經過去的日期。',
      'planner_today_earliest': '今天的景點最早只能安排在 {time}。',
      'planner_add_type_title': '選擇新增項目類型',
      'planner_keep_at_least_one': '行程中至少需要保留一個景點。',
      'planner_coordinates_missing': '以下行程項目缺少有效座標：{places}',
      'planner_coordinates_remove_hint': '請移除後重新產生行程。',
      'planner_progress_organizing': '正在整理景點限制…',
      'planner_progress_tdx_cancelled': '已取消 TDX 等待，正在以估計時間完成行程…',
      'planner_required_spot_remove': '{place} 是必去景點，若要移除，請返回修改旅遊需求。',
      'autofill_title': '智慧補齊景點',
      'autofill_overview': '目前已有 {current} 個景點。\n依照 {days} 天、{pace} 行程，建議安排 {target} 個景點。',
      'autofill_adding': '將補入 {count} 個景點：',
      'autofill_not_enough': '目前符合條件的景點不足，補入後仍少 {count} 個。',
      'autofill_cancel': '取消',
      'autofill_confirm': '補入 {count} 個景點',
      'autofill_already_full': '目前已有 {current} 個景點，已達建議數量 {target} 個。',
      'autofill_none_available': '目前沒有其他符合條件的推薦景點可以補入。',
      'autofill_success': '已補入 {count} 個推薦景點。',
      'pace_relaxed': '悠閒',
      'pace_intensive': '緊湊',
      'pace_balanced': '平衡',
      'itinerary_gps_tracking': 'GPS 追蹤中',
      'itinerary_drag_hint': '長按景點後拖到新的 Day 與時間；鎖定時段不接受放置。',
      'itinerary_reordering': '正在重排…',
      'itinerary_pending_drag': '暫定區｜請把新增的景點拖到課表',
      'itinerary_collapse_gaps': '壓縮空白時段',
      'itinerary_expand_gaps': '展開全部時段',
      'itinerary_collapsed_interval': '{start}:00–{end}:00 空白 · 點開／拖曳停留',
      'itinerary_time_axis': '時間',
      'itinerary_past_time': '此時間已經過去',
      'itinerary_slot_locked': '此時段已鎖定',
      'itinerary_drop_to_slot': '放到 Day {day} {time}',
      'itinerary_warning_count': '{count} 項行程提醒 · 查看',
      'itinerary_warning_title': '行程提醒',
      'dialog_close': '關閉',
      'itinerary_result_title': '行程規劃結果',
      'itinerary_map_hide': '隱藏地圖',
      'itinerary_map_show': '顯示地圖',
      'itinerary_tracking_stop': '停止追蹤',
      'itinerary_tracking_start': '開始行程',
      'itinerary_weather_simulate': '模擬惡劣天氣',
      'itinerary_edit': '編輯行程',
      'itinerary_export': '匯出行程',
      'itinerary_empty': '目前沒有可顯示的行程。',
      'itinerary_map_date': '地圖日期：',
      'itinerary_follow_trip': '跟隨行程（Day {day}）',
      'itinerary_zoom_out': '縮小行程表',
      'itinerary_zoom_in': '放大行程表',
      'itinerary_add_place': '新增景點',
      'itinerary_ai_understanding': '正在理解修改要求...',
      'itinerary_ai_edit': 'AI 協助修改',
      'itinerary_single_day': '單日課表',
      'itinerary_multi_day': '多日總覽',
      'picker_choose_type': '選擇{type}',
      'picker_close': '關閉',
      'picker_all': '全部',
      'picker_favorites': '我的收藏',
      'picker_search_hint': '搜尋名稱、分類或地址',
      'picker_clear_search': '清除搜尋',
      'picker_folders': '資料夾',
      'picker_all_favorites': '全部收藏 ({count})',
      'picker_uncategorized': '未分類景點 ({count})',
      'picker_counties': '縣市',
      'picker_all_counties': '全部縣市',
      'picker_no_favorites': '目前沒有符合條件的收藏{type}',
      'picker_no_places': '目前沒有符合條件的{type}',
      'picker_no_coordinates': '缺少座標，暫不可排入行程',
      'picker_stay': '停留 {minutes} 分鐘',
      'picker_selected': '已選 {count} 個{type}',
      'picker_apply': '套用選擇',
      'cloud_favorites_login': '請先登入以查看收藏',
      'cloud_favorites_failed': '收藏載入失敗，請重試',
      'cloud_favorites_loading': '正在載入收藏與資料夾…',
      'cloud_favorites_reload': '收藏載入失敗，重新載入',
      'favorite_picker_title': '從收藏加入景點',
      'favorite_picker_empty': '此分類暫無可加入的景點',
      'favorite_picker_add_count': '加入行程 ({count})',

      // 使用指南
      "welcome_title": "歡迎來到旅行旅伴！",
      "welcome_hint": "點擊任意處開始探索你的專屬行程，右上角可隨時再次開啟導引。",
      "navigation_hint_title": "底部切換導航",
      "navigation_hint_desc": "隨時在「首頁」、「行程安排」、「我的收藏」與「靈感搜尋」之間切換。"




    },
    'en': {
      // Global & Top Bar
      'guide': 'Guide',
      'login': 'Login',
      'account_center': 'Account Center',
      'logout': 'Log Out',
      'logout_success': 'Successfully logged out 🌿',
      'guest_traveler': 'Guest Traveler',
      'login_prompt': 'Sign in to sync your trips and favorites',

      // Bottom Navigation
      'nav_home': 'Home',
      'nav_trip': 'Itinerary',
      'nav_profile': 'Profile',
      'nav_inspiration': 'Inspiration',
      'nav_settings': 'Settings',

      // HomePage
      'popular_trips': 'Popular Community Trips',
      'view_trip': 'View Trip',
      'spot_recommendations': 'Recommended Spots',
      'view_detail': 'Details',
      'manual_schedule': 'Manual Planning',
      'min': 'mins',

      // TripPage
      'create_trip': 'Create New Trip',
      'trip_basic_info': 'Trip Basic Info',
      'trip_name': 'Trip Name',
      'trip_date': 'Trip Dates',
      'select_trip_date': 'Select trip dates',
      'trip_location': 'Destination',
      'trip_people': 'Travelers',
      'budget_level': 'Budget Level',
      'travel_pref_trip': 'Travel Preferences',
      'other_requirements': 'Other Requirements',

      // ProfilePage
      'my_favorites': 'My Favorites',
      'spots': 'Attractions',
      'itinerary': 'Trips',
      'my_folders': 'My Folders',
      'create_folder': 'Create Folder',
      'add_to_folder': 'Add to Folder',
      'add_to_trip': 'Add to Trip',
      'cancel_fav': 'Remove Favorite',
      'personal_space': 'Personal Space',
      'my_trips': 'My Trips',
      'my_trips_desc': 'Journeys planned and saved by you',
      'empty_trips': 'No saved trips yet. Tap "Export" after planning to save here 🌿',
      'saved_spots': 'Saved Spots',
      'empty_spots': 'No saved spots yet',
      'saved_trips': 'Saved Itineraries',
      'saved_folders': 'Saved Folders',
      'empty_folders': 'No folders created yet',
      'please_login_first': 'Please sign in first',
      'load_trips_failed': 'Failed to load itineraries',
      'delete_trip': 'Delete Itinerary',
      'delete_folder': 'Delete Folder',
      'delete_item_confirm': 'Delete “{name}”? This action cannot be undone.',
      'delete_action': 'Delete',
      'delete_success': 'Deleted',
      'delete_failed': 'Could not delete. Please try again.',

      // SettingsPage
      'settings_title': 'Settings',
      'logged_out_safe': 'Logged out safely',
      'logged_out_safe_leaf': 'Logged out safely 🌿',
      'logout_account': 'Log Out',
      'traveler': 'Traveler',
      'login_sync_hint': 'Sign in to sync custom trips and favorites',
      'login_action': 'Log In',
      'account_settings': 'Account Settings',
      'edit_profile': 'Edit Profile',
      'edit_profile_sub': 'Change avatar, nickname & bio',
      'travel_pref': 'Travel Preferences',
      'travel_pref_sub': 'Island leisure, adventure, gourmet',
      'notifications': 'Notifications',
      'notifications_sub': 'Receive spot alerts and promotions',
      'system_settings': 'Page & App Settings',
      'dark_mode': 'Dark Mode',
      'dark_mode_sub': 'Reduce glare in low-light environments',
      'language_setting': 'Language',
      'clear_cache': 'Clear Cache',
      'clear_cache_sub': '48.5 MB used',
      'clear_cache_title': 'Clear Cache',
      'clear_cache_content': 'Will clear cached images and offline data. Your favorites will not be affected.',
      'clear_cache_confirm': 'Clear Now',
      'clear_cache_cancel': 'Cancel',
      'clear_cache_success': 'Cache cleared successfully 🧹',
      'review_guide': 'Review User Guide',
      'about_app': 'About App',
      'select_language': 'Select Language',
      'register_title': 'Create Account',
      'register_email': 'Email',
      'register_password': 'Password',
      'confirm_password': 'Confirm Password',
      'terms_of_service': 'Terms of Service',
      'privacy_policy': 'Privacy Policy',

      // Shared page labels and messages
      'place_category_attraction': 'Attraction',
      'place_category_restaurant': 'Restaurant',
      'place_category_accommodation': 'Accommodation',
      'place_detail_intro': 'Introduction',
      'place_detail_address': 'Address',
      'place_detail_navigation': 'Navigate',
      'place_detail_empty_description': 'No detailed description available',
      'place_detail_stay': 'Suggested stay',
      'place_detail_minutes': 'min',
      'place_favorite_added': 'Added "{place}" to favorites ⭐️',
      'place_favorite_removed': 'Removed "{place}" from favorites',
      'place_phone_unavailable': 'Unable to open the phone app',
      'place_website_invalid': 'Invalid website URL',
      'place_website_unavailable': 'Unable to open the website',
      'search_trips_hint': 'Search trips...',
      'search_you_might_like': 'You might like...',
      'search_sort': '(Sort by)',
      'search_trip_use_count': '({count} uses)',
      'profile_view_info': 'View Details',
      'profile_folder_empty_detail': 'No spots in this folder yet\nChoose "Add to Folder" from a spot menu',
      'profile_no_folders': 'No folders yet',
      'profile_close': 'Close',
      'profile_create_folder': 'Create New Folder',
      'profile_folder_name_hint': 'Enter a folder name',
      'profile_cancel': 'Cancel',
      'profile_create': 'Create',
      'profile_folder_failed': 'Could not create folder. Please sign in and try again.',
      'profile_folder_add_failed': 'Could not add item. Please try again.',
      'profile_unnamed_trip': 'Untitled Trip',
      'profile_image': 'Image',
      'guide_finish': 'Tap to finish ❯',
      'guide_next': 'Tap for next step ❯',
      'guide_skip': 'Skip Guide',
      'edit_profile_title': 'Edit Profile',
      'edit_profile_change_avatar': 'Tap the camera to change your avatar',
      'edit_profile_avatar_notice': 'Avatar upload can be connected here',
      'edit_profile_default_bio': 'A travel companion who loves exploring the world 🌿',
      'edit_profile_nickname': 'Nickname',
      'edit_profile_nickname_hint': 'Enter your nickname',
      'edit_profile_nickname_required': 'Nickname is required',
      'edit_profile_email': 'Linked Email (Read-only)',
      'edit_profile_email_hint': 'Email address',
      'edit_profile_bio': 'Bio / Travel Quote',
      'edit_profile_bio_hint': 'Write a sentence or two about your travel style, such as a love of outdoor adventures...',
      'edit_profile_save': 'Save Changes',
      'edit_profile_saved': 'Profile synced successfully ✨',
      'edit_profile_load_failed': 'Failed to load profile',
      'edit_profile_save_failed': 'Failed to save',
      'login_success': 'Login successful! Welcome back 🌿',
      'login_invalid': 'Incorrect email or password',
      'login_error': 'An error occurred while logging in',
      'login_email_required': 'Enter your email address',
      'login_password_required': 'Enter your password',
      'login_contact_admin': 'Contact an administrator to reset your password',
      'register_action': 'Create Account',
      'trip_no_spots': 'There are no attractions to schedule',
      'trip_day_no_spots': 'No attractions are scheduled for this day',
      'trip_result_title': 'Your Itinerary',
      'guide_settings_title': 'Guide and Settings',
      'guide_settings_desc': 'Open the guide here, or change the app language in Settings.',
      'guide_nav_title': 'Switch Pages',
      'guide_nav_desc': 'Use the bottom navigation to switch between Home, Itinerary, Profile, and Settings.',
      'home_distance_sort': 'Sort by distance',
      'home_load_places_failed': 'Failed to load attractions',
      'home_no_places': 'No attractions available',
      'trip_select_date_first': 'Select your travel dates first',
      'trip_select_budget': 'Select a budget level',
      'trip_catalog_empty': 'No itinerary data is available',
      'trip_preference_parse_failed': 'Failed to parse AI preferences',
      'trip_create_failed': 'Failed to create trip',
      'search_hint': 'Search trips...',
      'search_recommendations': 'You might like...',
      'search_sort_label': '(Sort by)',
      'search_count_label': '({count} uses)',
      'register_subtitle': 'Join us and start your next adventure',
      'register_name_required': 'Enter your name',
      'register_email_required': 'Enter your email address',
      'register_email_invalid': 'Enter a valid email address',
      'register_password_short': 'Password must be at least 6 characters',
      'register_password_mismatch': 'Passwords do not match',
      'register_success': 'Account created! Your journey is about to begin ✈️',
      'register_failed': 'Sign up failed. Please try again later.',
      'register_have_account': 'Already have an account?',
      'register_login': 'Log In',
      'trip_date_not_selected': 'Not selected',
      'trip_date_select_prompt': 'Select travel dates',
      'trip_name_example': 'Example: Two days in Taipei',
      'trip_people_unit': 'people',
      'budget_save': 'Budget',
      'budget_affordable': 'Affordable',
      'budget_moderate': 'Moderate',
      'budget_upscale': 'Upscale',
      'budget_luxury': 'Luxury',
      'budget_scale_hint': '1 Lowest · 5 Highest',
      'trip_other_requirements_hint': 'For example: Keep the itinerary relaxed and avoid scheduling too many attractions',
      'trip_understanding_preferences': 'Understanding your travel preferences...',
      'trip_next_step': 'Next',
      'pref_food': 'Food',
      'pref_shopping': 'Shopping',
      'pref_culture': 'Culture',
      'pref_nature': 'Nature',
      'pref_photography': 'Photography',
      'pref_night_view': 'Night Views',
      'pref_family': 'Family',
      'pref_history': 'History',
      'pref_art': 'Art',
      'route_detail_title': 'Route Details',
      'route_departure': 'Start',
      'route_boarding': 'Boarding Point',
      'route_destination': 'Destination',
      'route_walk': 'Walk',
      'route_minutes': 'min',
      'route_under_minute': 'Under 1 min',
      'route_bus': 'Bus',
      'route_stop_count': '{duration} ({count} stops)',
      'route_wait': 'Wait {minutes} min',
      'recommended_itinerary': 'Recommended Itinerary',
      'search_places_hint': 'Search attractions, food, or places...',
      'create_trip_example': 'Example: One day in Taipei',
      'dialog_cancel': 'Cancel',
      'dialog_create': 'Create',
      'add_to_trip_dialog_title': 'Add to Trip',
      'add_to_trip_empty': 'No trips yet',
      'add_to_trip_spot_count': '{count} attractions',
      'add_to_trip_success': 'Added "{place}" to "{trip}"',
      'planner_title': 'Plan Itinerary',
      'planner_add_new': 'Add {type}',
      'planner_type_schedule': 'Plan {type}',
      'planner_conflict_title': 'Conflicting Travel Preferences',
      'planner_conflict_message': 'Some preferences also appear in the exclusions. Exclusions will take priority:',
      'planner_acknowledge': 'Got it',
      'planner_summary': 'Attractions {attractions} · Restaurants {restaurants} · Hotels {accommodations} | Fixed times {fixed} · Set dates {dated} · Auto-scheduled {automatic}',
      'planner_auto_fill': 'Smart Fill Attractions',
      'planner_generating': 'Planning detailed itinerary…',
      'planner_finish_generate': 'Finish and Create Detailed Itinerary',
      'planner_cancel_wait_estimate': 'Stop waiting and estimate remaining routes',
      'planner_unscheduled_type': 'Unscheduled {type}',
      'planner_unscheduled_auto': 'These {type} will be scheduled automatically',
      'planner_unscheduled_empty': 'No unscheduled items',
      'planner_select_day': 'Set Day',
      'planner_adjust_hotel': 'Adjust Stay',
      'planner_remove': 'Remove',
      'planner_any_day': 'Any Day',
      'planner_choose_day_first': 'Choose a day first',
      'planner_add_item_first': 'Add at least one itinerary item',
      'planner_generation_failed': 'Could not create the detailed itinerary',
      'planner_recommendation_reason': 'Why recommended: {reasons}',
      'planner_untimed_title': 'Unscheduled Time',
      'planner_timeline_title': 'Timeline',
      'planner_no_unscheduled_type': 'No unscheduled {type}',
      'planner_remove_type': 'Remove {type}',
      'planner_outside_range': 'This attraction is outside the default travel area, but is kept because it is a must-visit.',
      'planner_recommended_removable': 'Recommended by the system · You can remove it',
      'planner_adjust_accommodation': 'Adjust Stay',
      'planner_select_date': 'Set Date',
      'planner_any_date_time': 'Any Date / Time',
      'planner_day_time_unlimited': 'Day {day} · Any Time',
      'planner_locked_time': '{time} · Locked',
      'planner_preferences_tooltip': 'Time, duration, and information sources',
      'planner_choose_date': 'Choose Date',
      'planner_specify_time': 'Set Time',
      'planner_date_past': 'Attractions cannot be scheduled on a past date.',
      'planner_today_earliest': 'Today’s attractions can be scheduled no earlier than {time}.',
      'planner_add_type_title': 'Choose Item Type to Add',
      'planner_keep_at_least_one': 'Keep at least one attraction in the itinerary.',
      'planner_coordinates_missing': 'These itinerary items have no valid coordinates: {places}',
      'planner_coordinates_remove_hint': 'Remove them and generate the itinerary again.',
      'planner_progress_organizing': 'Preparing attraction constraints…',
      'planner_progress_tdx_cancelled': 'TDX wait cancelled. Finishing the itinerary with estimated times…',
      'planner_required_spot_remove': '{place} is a must-visit. Return to travel preferences to remove it.',
      'autofill_title': 'Smart Fill Attractions',
      'autofill_overview': 'You currently have {current} attractions.\nFor a {days}-day {pace} itinerary, we recommend {target} attractions.',
      'autofill_adding': 'The following {count} attractions will be added:',
      'autofill_not_enough': 'There are not enough matching attractions. {count} will still be missing after filling.',
      'autofill_cancel': 'Cancel',
      'autofill_confirm': 'Add {count} Attractions',
      'autofill_already_full': 'You already have {current} attractions, meeting the recommended total of {target}.',
      'autofill_none_available': 'There are no more recommended attractions that match your criteria.',
      'autofill_success': 'Added {count} recommended attractions.',
      'pace_relaxed': 'relaxed',
      'pace_intensive': 'intensive',
      'pace_balanced': 'balanced',
      'itinerary_gps_tracking': 'GPS tracking',
      'itinerary_drag_hint': 'Long-press an attraction and drag it to a new day and time. Locked time slots cannot accept drops.',
      'itinerary_reordering': 'Reordering…',
      'itinerary_pending_drag': 'Pending · Drag added attractions onto the timetable',
      'itinerary_collapse_gaps': 'Collapse empty hours',
      'itinerary_expand_gaps': 'Expand all hours',
      'itinerary_collapsed_interval': '{start}:00–{end}:00 empty · Tap or hold to expand',
      'itinerary_time_axis': 'Time',
      'itinerary_past_time': 'This time has passed',
      'itinerary_slot_locked': 'This time slot is locked',
      'itinerary_drop_to_slot': 'Drop on Day {day} at {time}',
      'itinerary_warning_count': '{count} itinerary alerts · View',
      'itinerary_warning_title': 'Itinerary Alerts',
      'dialog_close': 'Close',
      'itinerary_result_title': 'Itinerary Plan',
      'itinerary_map_hide': 'Hide Map',
      'itinerary_map_show': 'Show Map',
      'itinerary_tracking_stop': 'Stop Tracking',
      'itinerary_tracking_start': 'Start Trip',
      'itinerary_weather_simulate': 'Simulate Severe Weather',
      'itinerary_edit': 'Edit Itinerary',
      'itinerary_export': 'Export Itinerary',
      'itinerary_empty': 'There is no itinerary to display.',
      'itinerary_map_date': 'Map Date:',
      'itinerary_follow_trip': 'Follow Trip (Day {day})',
      'itinerary_zoom_out': 'Zoom Out',
      'itinerary_zoom_in': 'Zoom In',
      'itinerary_add_place': 'Add Attraction',
      'itinerary_ai_understanding': 'Understanding your edit...',
      'itinerary_ai_edit': 'AI Edit',
      'itinerary_single_day': 'Single Day',
      'itinerary_multi_day': 'All Days',
      'picker_choose_type': 'Select {type}',
      'picker_close': 'Close',
      'picker_all': 'All',
      'picker_favorites': 'My Favorites',
      'picker_search_hint': 'Search by name, category, or address',
      'picker_clear_search': 'Clear Search',
      'picker_folders': 'Folders',
      'picker_all_favorites': 'All Favorites ({count})',
      'picker_uncategorized': 'Uncategorized ({count})',
      'picker_counties': 'County/City',
      'picker_all_counties': 'All Counties/Cities',
      'picker_no_favorites': 'No matching saved {type}',
      'picker_no_places': 'No matching {type}',
      'picker_no_coordinates': 'Missing coordinates; cannot add to itinerary yet',
      'picker_stay': 'Stay {minutes} min',
      'picker_selected': '{count} {type} selected',
      'picker_apply': 'Apply Selection',
      'cloud_favorites_login': 'Sign in to view favorites',
      'cloud_favorites_failed': 'Failed to load favorites. Try again.',
      'cloud_favorites_loading': 'Loading favorites and folders…',
      'cloud_favorites_reload': 'Failed to load favorites. Reload',
      'favorite_picker_title': 'Add Attractions from Favorites',
      'favorite_picker_empty': 'No attractions in this category',
      'favorite_picker_add_count': 'Add to Trip ({count})',

      //register screen

      // 使用指南
      "welcome_title": "Welcome to Travel Companion!",
      "welcome_hint": "Tap anywhere to explore your personalized itinerary. Tap the top right anytime to reopen this guide.",
      "navigation_hint_title": "Bottom Navigation",
      "navigation_hint_desc": "Switch anytime between Home, Itinerary, Favorites, and Explore."
    },
  };
}
